fix text overlap on mobile issue
datamade/la-metro-councilmatic pull request #719
Opened 2021-04-14 19:56 UTC by fatima3558

## Overview

This PR addresses an issue on mobile devices where the text under the home page search bar overlaps with the heading for the next section.

### Checklist

- [x] PR has a descriptive enough title to be useful in changelogs

### Demo
<img width="545" alt="Screen Shot 2021-04-14 at 2 54 27 PM" src="https://user-images.githubusercontent.com/48227264/114770741-61850d00-9d31-11eb-9a3d-e290d9b58fd0.png">

## Testing Instructions

 * run the app locally and use your browser's device toolbar to toggle mobile view
 * make sure none of the text on the home page overlaps

Handles #350

2021-04-14 20:44 UTC, hancush requested changes
Hm, I'm still seeing the overlap on sufficiently small screens. 

<img width="1552" alt="Screen Shot 2021-04-14 at 3 44 20 PM" src="https://user-images.githubusercontent.com/12176173/114776615-4a95e900-9d38-11eb-964a-7e87d92f2457.png">

Is there a fixed height on the `section-photo` class, by chance?

2021-04-14 20:45 UTC, hancush commented
P.s., I think the contemporary version of this issue is #674.

2021-04-14 20:55 UTC, fatima3558 commented
when you say you still see the overlap, is it because part of the text is on a white background?

And I did look at the `section-photo` class. There is not a fixed height, but there is a minimum height. I can play around with the image size and position, see if I can get closer to what we need.

2021-04-20 18:47 UTC, hancush requested changes
Looking good! One small tweak suggested inline.

2021-04-20 18:47 UTC, hancush commented on lametro/templates/lametro/index.html
> +    <div id="section-photo">
How about retaining `.container-fluid` to preserve padding on smaller screens?

```suggestion
    <div id="section-photo" class="container-fluid">
```

Without:

![Screen Shot 2021-04-20 at 1 46 21 PM](https://user-images.githubusercontent.com/12176173/115448048-d4353300-a1de-11eb-870a-6183f8f7b5b3.png)

With:

![Screen Shot 2021-04-20 at 1 45 13 PM](https://user-images.githubusercontent.com/12176173/115448057-d7c8ba00-a1de-11eb-86f4-75808157b45d.png)

2021-04-20 19:10 UTC, hancush approved these changes

2021-04-20 19:38 UTC, merged